import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { PatientRecord } from './patient-records.model';

@Injectable({
  providedIn: 'root',
})
export class PatientRecordsService {
  private data: PatientRecord[] = [
    {
      id: 1,
      patientId: 'P-001',
      name: 'John Doe',
      img: 'assets/images/user/user1.jpg',
      age: 45,
      gender: 'Male',
      bloodGroup: 'A+',
      email: 'john.doe@example.com',
      mobile: '+1234567890',
      address: '123 Main St',
      city: 'New York',
      state: 'NY',
      registrationDate: '2023-01-10',
      lastVisitDate: '2023-10-25',
      totalVisits: 5,
      status: 'Active',
    },
    {
      id: 2,
      patientId: 'P-002',
      name: 'Jane Smith',
      img: 'assets/images/user/user2.jpg',
      age: 32,
      gender: 'Female',
      bloodGroup: 'B-',
      email: 'jane.smith@example.com',
      mobile: '+0987654321',
      address: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      registrationDate: '2023-02-15',
      lastVisitDate: '2023-10-26',
      totalVisits: 3,
      status: 'Critical',
    },
    {
      id: 3,
      patientId: 'P-003',
      name: 'Mike Johnson',
      img: 'assets/images/user/user3.jpg',
      age: 28,
      gender: 'Male',
      bloodGroup: 'O+',
      email: 'mike.johnson@example.com',
      mobile: '+1122334455',
      address: '789 Pine Rd',
      city: 'Chicago',
      state: 'IL',
      registrationDate: '2023-03-20',
      lastVisitDate: '2023-10-27',
      totalVisits: 2,
      status: 'Inactive',
    },
    {
      id: 4,
      patientId: 'P-004',
      name: 'Emily Davis',
      img: 'assets/images/user/user4.jpg',
      age: 52,
      gender: 'Female',
      bloodGroup: 'AB+',
      email: 'emily.davis@example.com',
      mobile: '+1445566778',
      address: '321 Maple Dr',
      city: 'Houston',
      state: 'TX',
      registrationDate: '2023-04-12',
      lastVisitDate: '2023-10-28',
      totalVisits: 8,
      status: 'Active',
    },
    {
      id: 5,
      patientId: 'P-005',
      name: 'Chris Lee',
      img: 'assets/images/user/user5.jpg',
      age: 38,
      gender: 'Male',
      bloodGroup: 'O-',
      email: 'chris.lee@example.com',
      mobile: '+1556677889',
      address: '654 Birch Ln',
      city: 'Phoenix',
      state: 'AZ',
      registrationDate: '2023-05-05',
      lastVisitDate: '2023-10-29',
      totalVisits: 4,
      status: 'Active',
    },
    {
      id: 6,
      patientId: 'P-006',
      name: 'Anna Brown',
      img: 'assets/images/user/user6.jpg',
      age: 26,
      gender: 'Female',
      bloodGroup: 'A-',
      email: 'anna.brown@example.com',
      mobile: '+1667788990',
      address: '987 Cedar Way',
      city: 'Philadelphia',
      state: 'PA',
      registrationDate: '2023-06-18',
      lastVisitDate: '2023-10-30',
      totalVisits: 1,
      status: 'Active',
    },
    {
      id: 7,
      patientId: 'P-007',
      name: 'David Wilson',
      img: 'assets/images/user/user7.jpg',
      age: 60,
      gender: 'Male',
      bloodGroup: 'B+',
      email: 'david.wilson@example.com',
      mobile: '+1778899001',
      address: '159 Walnut St',
      city: 'San Antonio',
      state: 'TX',
      registrationDate: '2023-07-22',
      lastVisitDate: '2023-10-31',
      totalVisits: 10,
      status: 'Critical',
    },
    {
      id: 8,
      patientId: 'P-008',
      name: 'Laura White',
      img: 'assets/images/user/user8.jpg',
      age: 34,
      gender: 'Female',
      bloodGroup: 'AB-',
      email: 'laura.white@example.com',
      mobile: '+1889900112',
      address: '753 Ash Ct',
      city: 'San Diego',
      state: 'CA',
      registrationDate: '2023-08-14',
      lastVisitDate: '2023-11-01',
      totalVisits: 6,
      status: 'Active',
    },
    {
      id: 9,
      patientId: 'P-009',
      name: 'James Miller',
      img: 'assets/images/user/user9.jpg',
      age: 42,
      gender: 'Male',
      bloodGroup: 'A+',
      email: 'james.miller@example.com',
      mobile: '+1990011223',
      address: '852 Elm Rd',
      city: 'Dallas',
      state: 'TX',
      registrationDate: '2023-09-01',
      lastVisitDate: '2023-11-02',
      totalVisits: 3,
      status: 'Inactive',
    },
    {
      id: 10,
      patientId: 'P-010',
      name: 'Sophia Taylor',
      img: 'assets/images/user/user10.jpg',
      age: 29,
      gender: 'Female',
      bloodGroup: 'O+',
      email: 'sophia.taylor@example.com',
      mobile: '+1001122334',
      address: '369 Maple Blvd',
      city: 'San Jose',
      state: 'CA',
      registrationDate: '2023-09-15',
      lastVisitDate: '2023-11-03',
      totalVisits: 2,
      status: 'Active',
    },
    {
      id: 11,
      patientId: 'P-011',
      name: 'Lucas Martinez',
      img: 'assets/images/user/user11.jpg',
      age: 48,
      gender: 'Male',
      bloodGroup: 'B-',
      email: 'lucas.martinez@example.com',
      mobile: '+1112233445',
      address: '258 Oak Rd',
      city: 'Austin',
      state: 'TX',
      registrationDate: '2023-10-01',
      lastVisitDate: '2023-11-04',
      totalVisits: 5,
      status: 'Active',
    },
    {
      id: 12,
      patientId: 'P-012',
      name: 'Isabella Rodriguez',
      img: 'assets/images/user/user2.jpg',
      age: 31,
      gender: 'Female',
      bloodGroup: 'AB+',
      email: 'isabella.rodriguez@example.com',
      mobile: '+1223344556',
      address: '159 Pine St',
      city: 'Jacksonville',
      state: 'FL',
      registrationDate: '2023-10-10',
      lastVisitDate: '2023-11-05',
      totalVisits: 2,
      status: 'Active',
    },
  ];

  private dataSubject = new BehaviorSubject<PatientRecord[]>(this.data);

  constructor() {}

  getAllPatientRecords(): Observable<PatientRecord[]> {
    return this.dataSubject.asObservable();
  }

  addPatientRecord(patient: PatientRecord): void {
    patient.id = this.data.length + 1;
    this.data.unshift(patient);
    this.dataSubject.next(this.data);
  }

  updatePatientRecord(patient: PatientRecord): void {
    const index = this.data.findIndex((d) => d.id === patient.id);
    if (index !== -1) {
      this.data[index] = patient;
      this.dataSubject.next(this.data);
    }
  }

  deletePatientRecord(id: number): void {
    this.data = this.data.filter((d) => d.id !== id);
    this.dataSubject.next(this.data);
  }
}
